package com.capgemini.ui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;
import java.util.Scanner;

import com.capgemini.dto.DiagnosticCenter;
import com.capgemini.healthcare.exceptions.MyException;
import com.capgemini.dto.CenterTest;
import com.capgemini.service.ServiceImplementation;
import com.capgemini.service.Validation;
import com.capgemini.util.*;

public class Client {

	public static void main(String[] args) throws IOException {
		Scanner input=new Scanner(System.in);
		ServiceImplementation serviceObject = new ServiceImplementation();
		Validation v = new Validation();
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		List<DiagnosticCenter> viewCenters;
		System.out.println("\n---Welcome to admin panel---");
		
		while(true)
		{
			System.out.println();
			System.out.println("Enter 1 to add center");
			System.out.println("Enter 2 to remove center");
			System.out.println("Enter 3 to add test");
			System.out.println("Enter 4 to remove test");
			System.out.println("Enter 5 to view centers");
			System.out.println("Enter 6 to view centers and their corresponding tests");
			System.out.println("Enter 7 to exit");
			String choice=null;
			try {
			 choice = input.next();
			 if(!choice.matches("[0-9]*")) {
				 throw new MyException("ONLY INTEGERS ARE ALLOWED");
			 }
			 switch(choice)
				{
		
				case "1":
		
					System.out.println("\n*Note: Center name should not be blank, fist letter should be capital and it should not be there in Center list");
					System.out.println("\nEnter Center Name");
					while(true)
					{
						String centerName=br.readLine();
						if(v.validateCenterName(centerName))
							{
							    if(serviceObject.isCenterNamePresent(centerName))
							    {
							    	try
							    	{
							    	throw new MyException("Center Name already there in the list");
							    	}
							    	catch(MyException nameAlreadyExits)
							    	{
							    	    System.out.println(nameAlreadyExits.getMessage());
							    		System.out.println("\nEnter the center name again that does not exit in the center List");
							    		continue;
							    	}
							    }
								serviceObject.addCenter(new DiagnosticCenter(CollectionUtil.centerAutogeneratedId(),centerName));
								System.out.println("Center added sucessfully");
								break;	
							}
					}
					break;
					
				case "2":
					
					System.out.println();
					System.out.println();
					viewCenters = serviceObject.viewCenters();
					System.out.println("Center Id"+"        "+"Center Name");
					for(DiagnosticCenter dc:viewCenters)
					{
						System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
					}
					System.out.println("\n*Note: Center Id should not be there in Center list");
					System.out.println("\nEnter the id of the center from the above centers list to delete");
					while(true)
					{
						String centerId = br.readLine();
						if(v.validateCenterId(centerId))
						{
							DiagnosticCenter centerObject = serviceObject.getCenterObjectOfcenterId(centerId); //getting the centerObject corresponding to the centerId.
							serviceObject.removeCenter(centerObject); //calling the removeCenter method of the serviceImplementation class.
							System.out.println("Center removed successfully");
							break;
						}
						else
						{
							System.out.println("Enter the center Id again that exit in the center list.");
						}
					}
					break;
					
				case "3":
					
					System.out.println();
					System.out.println();
					viewCenters = serviceObject.viewCenters();
					System.out.println("Center Id"+"        "+"Center Name");
					for(DiagnosticCenter dc:viewCenters)
					{
						System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
					}
					System.out.println("\nEnter the id of the center from the above centers to add the test in that corressponding center");
					while(true)
					{
						String center_Id = br.readLine();
						if(v.validateCenterId(center_Id))
						{
							System.out.println("Enter the test name you want to add");
							while(true)
							{
								String testName = br.readLine();
								DiagnosticCenter centerObject = serviceObject.getCenterObjectOfcenterId(center_Id);
								if(v.validateCenterTest(centerObject,testName))
								{
									serviceObject.addTest(centerObject,new CenterTest(CollectionUtil.testAutogeneratedId(),testName));//here addTest of the ServiceImplementation class is taking two parameters one is the object of the centerArraylist and the other parameter is the name of the test to add in that center.
									System.out.println("Test successfully added to the "+centerObject.getCenterName());
									break;
								}
								else
								{
									System.out.println("\nEnter the test name that you want to add which does not exist in "+centerObject.getCenterName());
								}
							}
							break;
						}
						else
						{
							System.out.println("\nEnter the id of the center that exists in the center list");
						}
					}
					break;
					
				case "4":
					
					System.out.println();
					System.out.println();
					viewCenters = serviceObject.viewCenters();
					System.out.println("Center Id"+"        "+"Center Name");
					for(DiagnosticCenter dc:viewCenters)
					{
						System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
					}
					System.out.println("Enter the id of the center from the above centers to remove their corressponding test");
					while(true)
					{
						String center_id = br.readLine();
						if(v.validateCenterId(center_id))
						{
							serviceObject.viewCenterRepectiveTests(center_id);
							System.out.println("\nEnter the id of the test from the above respective center tests to remove the test");
							while(true)
							{
								String test_Id = br.readLine();
								DiagnosticCenter centerObject = serviceObject.getCenterObjectOfcenterId(center_id);
								if(v.validateCenterTestId(centerObject,test_Id))
								{
									CenterTest t = serviceObject.getTestObject(centerObject,test_Id);
									serviceObject.removeTest(centerObject, t);
									System.out.println("Test Successfully removed from "+serviceObject.getCenterObjectOfcenterId(center_id).getCenterName());
									break;
								}
								else
								{
									System.out.println("\nEnter the test id that you want to delete which exists in "+centerObject.getCenterName()+"test list");
								}
							}
							break;
						}
						else
						{
							System.out.println("\nEnter the id of the center that exists in the center list");
						}
					}
					break;
					
				case "5":
					
					System.out.println();
					viewCenters = serviceObject.viewCenters();
					System.out.println("Center Id"+"        "+"Center Name");
					for(DiagnosticCenter dc:viewCenters)
					{
						System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
					}
					break;
					
				case "6":
					
					System.out.println();
					serviceObject.viewCentersAndTests();
					break;
					
				case "7":
					
					System.out.println("THANK YOU FOR VISITING");
					System.exit(0);
					break;
					
				default:
					System.out.println("....INVALID INPUT ENTER THE RESPECTIVE NUMBER MENTIONED IN THE BELOW LIST...");
					break;
				}
			}
			catch (MyException inputMisMatchException) {
				// TODO: handle exception
				System.out.println(inputMisMatchException.getMessage());
			}
		}
	}
}
